name: ExecutableItems
version: ${project.version}
main: com.ssomar.executableitems.ExecutableItems
api-version: 1.13
author: Ssomar
description: Execute a command with item.
softdepend: [PlayerPoints,Vault]
commands:
  ei-reload:
    description: reload command
    usage: "/ei-reload"
    permission: ei.cmd.reload
  ei-give:
    description: give command
    usage: "/ei-give"
    permission: ei.cmd.give
  ei-giveall:
    description: giveall command
    usage: "/ei-giveall"
    permission: ei.cmd.giveall
  ei-show:
    description: show avaible items
    usage: "/ei-show"
    permission: ei.cmd.show
  ei-actionbar:
    description: active/desactive actionbar
    usage: "/ei-actionbar"
    permission: ei.cmd.actionbar
  ei-create:
    description: create new ExecutableItem
    usage: "/ei-create"
    permission: ei.cmd.create
